### ISSUE TITLE
iOS 11 Large gap above scroll view

### ISSUE THREAD

**Issue by joshbernfeld** [telly/TLYShyNavBar#190]
I was experiencing an issue on iOS 11 where there was a gap above the scroll view before the navigation bar. The solution for me was the following code. It seems that in addition to the content inset TLY was adding, iOS was then adding another inset which can be seen in the new variable adjustedContentInset

https://developer.apple.com/documentation/uikit/uiscrollview/2902259-adjustedcontentinset

This was my solution
```
if (@available(iOS 11.0, *)) {
    self.tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
}
```

**Comment by StainlessStlRat** [comment]
Were you able to work around it?

**Comment by n4nachiket** [comment]
Facing same issue

**Comment by joshbernfeld** [comment]
If you place the above code into the view controller that has your table view it should fix it

**Comment by stevekim0417** [comment]
@joshbernfeld Great!. It is helpful to me!

**Comment by StefaniOSApps** [comment]
you can also use:

`[[self shyNavBarManager] setHasCustomRefreshControl:YES];`

**Comment by StainlessStlRat** [comment]
I still get weird behavior where there are gaps when a view is swapped back in in a custom tab bar implementation.  Setting it to use has custom refresh control starts the table view underneath the bar.
